theme: jekyll-theme-minimal
title: Cameron's Homepage
description: For project hosting https://cameronkinnear.github.io/FromSoftMessageMaker/
pages:
 - https://cameronkinnear.github.io/FromSoftMessageMaker/
